### ISSUE TITLE
2.80

### ISSUE THREAD

**Issue by saucissevolante** [tin2tin/ExportEDL#3]
Hi there,
I have an issue with the version I've downloaded, once installed, Blender show me this line : Upgrade to 2.8x required
I'm using Blender 2.8. Maybe something I did not do well ?
( Thanks for your tool, It might help me to same some precious time ! )

**Comment by tin2tin** [comment]
I forgot to update the version number. Try now.

**Comment by saucissevolante** [comment]
It looks ok. Thanks !

**Comment by saucissevolante** [comment]
It looks ok. Thanks !

**Comment by tin2tin** [comment]
Great. Thanks.
