### ISSUE TITLE
EDL File doesn't work

### ISSUE THREAD

**Issue by vincentbien** [tin2tin/ExportEDL#4]
FCM: NON DROP FRAME

**Comment by tin2tin** [comment]
Please explain in a bit more detail what is the problem? I do notice you have closed the issue, but what is your finding?

**Comment by vincentbien** [comment]
> Please explain in a bit more detail what is the problem? I do notice you have closed the issue, but what is your finding?

I found that EDL File contained nothing while there were only image files on my timeline.

**Comment by tin2tin** [comment]
Ah yes, images are not supported: 
![image](https://github.com/tin2tin/Export_EDL/assets/1322593/0a53369b-0d69-4b82-adca-c4a76a4d659d)

Afaik, there are no working Blender add-ons to export edits with image/image sequences. 

As a workaround, you can convert your images to movie strips with this add-on: https://github.com/tin2tin/Add_Rendered_Strips

And for exporting to ex. Davinci Resolve(the latest release), this may be a better solution: https://github.com/tin2tin/VSE_OTIO_Export
